# ***Math Operation***

In [4]:
import pandas as pd

data_house = pd.read_csv("california_housing_train (1).csv")

data_house.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [5]:
other_rooms = data_house['total_rooms'] - data_house['total_bedrooms']

other_rooms

0        4329.0
1        5749.0
2         546.0
3        1164.0
4        1128.0
          ...
16995    1823.0
16996    1821.0
16997    2146.0
16998    2120.0
16999    1520.0
Length: 17000, dtype: float64

In [6]:
data_house['other_rooms'] = other_rooms

data_house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,other_rooms
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,4329.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,5749.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,546.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,1164.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,1128.0
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,1823.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,1821.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,2146.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,2120.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,1520.0

In [7]:
kepadatan = data_house['population'].div(data_house['households'])

kepadatan

0        2.150424
1        2.438445
2        2.846154
3        2.278761
4        2.381679
           ...
16995    2.457995
16996    2.567742
16997    2.728070
16998    2.715481
16999    2.985185
Length: 17000, dtype: float64

In [8]:
data_house = data_house.assign(kepadatan = kepadatan)
data_house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,other_rooms,kepadatan
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,4329.0,2.150424
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,5749.0,2.438445
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,546.0,2.846154
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,1164.0,2.278761
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,1128.0,2.381679
...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,1823.0,2.457995
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,1821.0,2.567742
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,2146.0,2.728070
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,2120.0,2.715481
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,1520.0,2.985185

In [11]:
total_ruang = data_house[['total_rooms','total_bedrooms','other_rooms']]
total_ruang

       total_rooms  total_bedrooms  other_rooms
0           5612.0          1283.0       4329.0
1           7650.0          1901.0       5749.0
2            720.0           174.0        546.0
3           1501.0           337.0       1164.0
4           1454.0           326.0       1128.0
...            ...             ...          ...
16995       2217.0           394.0       1823.0
16996       2349.0           528.0       1821.0
16997       2677.0           531.0       2146.0
16998       2672.0           552.0       2120.0
16999       1820.0           300.0       1520.0

[17000 rows x 3 columns]