In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
dataset = sns.load_dataset('diamonds')

In [6]:
dataset.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [9]:
dataset['cut'] = dataset['cut'].astype('category')
dataset['cut_encodes'] = dataset['cut'].cat.codes
dataset[['cut','cut_encodes']]

             cut  cut_encodes
0          Ideal            0
1        Premium            1
2           Good            3
3        Premium            1
4           Good            3
...          ...          ...
53935      Ideal            0
53936       Good            3
53937  Very Good            2
53938    Premium            1
53939      Ideal            0

[53940 rows x 2 columns]

In [33]:
by_cut = dataset.groupby('cut')
Premium = by_cut.get_group('Premium')
banyak_premium = Premium.__len__()
print(f"Banyak diamonds dengan kualitas premium ada sebanyak {banyak_premium} unit")

Banyak diamonds dengan kualitas premium ada sebanyak 13791 unit

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cut_category = le.fit_transform(dataset['cut'])

In [41]:
cut_category

array([2, 3, 1, ..., 4, 3, 2], shape=(53940,))

In [42]:
le.inverse_transform(cut_category)

array(['Ideal', 'Premium', 'Good', ..., 'Very Good', 'Premium', 'Ideal'],
      shape=(53940,), dtype=object)

In [43]:
pd.get_dummies(dataset['cut'])

       Ideal  Premium  Very Good   Good   Fair
0       True    False      False  False  False
1      False     True      False  False  False
2      False    False      False   True  False
3      False     True      False  False  False
4      False    False      False   True  False
...      ...      ...        ...    ...    ...
53935   True    False      False  False  False
53936  False    False      False   True  False
53937  False    False       True  False  False
53938  False     True      False  False  False
53939   True    False      False  False  False

[53940 rows x 5 columns]

# *Menggunakan sklearn*

In [45]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
cut_category2 = ohe.fit_transform(dataset[['cut']])

In [47]:
cut_category2.toarray()

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]], shape=(53940, 5))

In [48]:
pd.DataFrame(cut_category2.toarray())

         0    1    2    3    4
0      0.0  0.0  1.0  0.0  0.0
1      0.0  0.0  0.0  1.0  0.0
2      0.0  1.0  0.0  0.0  0.0
3      0.0  0.0  0.0  1.0  0.0
4      0.0  1.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...
53935  0.0  0.0  1.0  0.0  0.0
53936  0.0  1.0  0.0  0.0  0.0
53937  0.0  0.0  0.0  0.0  1.0
53938  0.0  0.0  0.0  1.0  0.0
53939  0.0  0.0  1.0  0.0  0.0

[53940 rows x 5 columns]